### ISSUE TITLE
gray out past events. highlight upcoming events

### ISSUE THREAD

**Issue by vinhnx** [vinhnx/Clendar#146]
event list

**Comment by vinhnx** [comment]
hi @AlexanderSutul

Yes, you're welcome to fork and implement this feature. Any contribution is more than welcome 🙏 

Let me know if you find any trouble. Thanks!

**Comment by AlexanderSutul** [comment]
@vinhnx Could you, please, describe a little bit your vision of this issue?
Any design details?

**Comment by vinhnx** [comment]
hi @AlexanderSutul , thank you for taking further !

Okay, the concept is pretty simple. If you look at the stock Calendar app, past events will be grayed out, while current and upcoming events are highlighted (as normal).

![Simulator Screen Shot - iPhone 12 mini - 2021-05-15 at 18 05 07](https://user-images.githubusercontent.com/1097578/118358350-8f67a680-b5a8-11eb-973c-178b2852c73a.png)

**Comment by vinhnx** [comment]
The event list row class is `EventListRow.swift`

https://github.com/vinhnx/Clendar/blob/main/Clendar/Modules/Event%20List/EventListRow.swift#L29-L33

Hint: you can compare current time and event's start time to change the row's text color as per condition.

Thank you!

**Comment by AlexanderSutul** [comment]
Thanks for the fast response.

**Comment by AlexanderSutul** [comment]
#150 Look at this PR, please.

**Comment by vinhnx** [comment]
thanks @AlexanderSutul 

I will check it out soon. thanks so much for your contribution

**Comment by vinhnx** [comment]
updated with some modification
![Simulator Screen Shot - iPhone 12 mini - 2021-05-16 at 09 08 00](https://user-images.githubusercontent.com/1097578/118383236-376f8500-b626-11eb-9a17-e547795c8d7c.png)

**Comment by AlexanderSutul** [comment]
Looks good  👍
