### ISSUE TITLE
new calendar event view using EventKit doesn’t work

### ISSUE THREAD

**Issue by vinhnx** [vinhnx/Clendar#149]
maybe since iOS 14.5.

it's showing blank page. 

using quick event view for now

**Comment by AlexanderSutul** [comment]
Hey! Feel free to assign this issue to me. I think I'll find a time to fix it during this week.

**Comment by vinhnx** [comment]
sure thanks @AlexanderSutul 🙏

**Comment by AlexanderSutul** [comment]
@vinhnx  Hey! Which view do we need to use for creating a new callendar event?

**Comment by vinhnx** [comment]
Please check: https://github.com/vinhnx/Clendar/blob/main/Clendar/Base/ContentView.swift#L78-L89

But please keep user's preference:
1. if `SettingsManager.useExperimentalCreateEventMode` flag is `true` => use current "quick event mote", which has natural language parsing (buggy but still works)
2. else, use [EventEditorWrapperView](https://github.com/vinhnx/Clendar/blob/main/Clendar/Modules/Event%20Editor/EventEditorWrapperView.swift), which wraps [EventEditViewController.swift](https://github.com/vinhnx/Clendar/blob/main/Clendar/Modules/Event%20Editor/EventEditViewController.swift) that is subclass of EventKit's `EKEventEditViewController`.

For point 2, it support to be like this. ![Simulator Screen Shot - iPhone 8 - 2021-05-20 at 09 09 40](https://user-images.githubusercontent.com/1097578/118908198-22a73000-b94b-11eb-9823-3f49d5de5e26.png)

problem is that I observe on iOS 14.5 onwards, the EventEditorWrapperView doesn't work any and showing blank screen, which was fine during previous iOS version.

I'm appreciated if you have the time to investigate this issue, since I'm currently busy with life/day-job. Thank you so much!

**Comment by AlexanderSutul** [comment]
@vinhnx I'll try, don't start working on it. I wanna fix it on my own. Please =)

**Comment by vinhnx** [comment]
ok sure, you can go ahead haha! @AlexanderSutul

**Comment by AlexanderSutul** [comment]
Hey! I've checked everything I could but got no idea what is going on here with this view... Could you check, pls and post the reason why it doesn't work here, please? 😊

**Comment by vinhnx** [comment]
> Hey! I've checked everything I could but got no idea what is going on here with this view... Could you check, pls and post the reason why it doesn't work here, please? 😊  (Feel free to assign something on me, I'll try to solve)

hi @AlexanderSutul , sorry for the late reply!

For this bug. Let me investigate, it couldn't be some changes to the SwiftUI and UIKit integration. Could it work on the latest iOS 15 beta. 

Anyway, thank you so much for your spirit. Have a nice day!

**Comment by vinhnx** [comment]
done #166 

turns out `EKEventEditViewController` instance need an non-empty EKEvent
