### ISSUE TITLE
Buy a real domain

### ISSUE THREAD

**Issue by vinhnx** [vinhnx/Clendar#152]
yes please!

**Comment by andyferriby** [comment]
What domain you looking for as i can get them cheap as chips

**Comment by vinhnx** [comment]
related to https://github.com/vinhnx/Clendar/issues/151

**Comment by vinhnx** [comment]
> What domain you looking for as i can get them cheap as chips

hi Andy, thanks for your reply. I think I need to think about a new marketing app name first. 

But a .co domain is good. For example: clendarapp.co

I thought about buying this and setup in the first place back then. But somehow I missed this. 😄

**Comment by vinhnx** [comment]
bought and setup https://www.clendar.info
