### ISSUE TITLE
bugs

### ISSUE THREAD

**Issue by vinhnx** [vinhnx/Clendar#167]
Love the app, but I’m encountering two bugs:
- “Follow system” theme is not working: the app is  stuck in Dark mode even when I’m Light mode (see attached video).  check: https://sarunw.com/posts/what-is-environment-in-swiftui/
- Home Screen Widgets for the app are not appearing as an option in the Widget selector.

**Comment by kapucnov2321** [comment]
Follow system theme was fixed. I will create PR in a minute. Home Screen Widgets are appearing for me in widget selector so i didnt fixed that.

**Comment by vinhnx** [comment]
thanks @kapucnov2321 !

**Comment by kapucnov2321** [comment]
@vinhnx Pull request created ! :)

**Comment by vinhnx** [comment]
fixed on #171
