### ISSUE TITLE
add github to settings page

### ISSUE THREAD

**Issue by vinhnx** [vinhnx/Clendar#212]

**Comment by prabal4546** [comment]
Hi, do u want to add the link to Github page of the app in settings or anything else?

**Comment by vinhnx** [comment]
hi @prabal4546 for this feature, I would like to add a row item into the app's settings page that would redirect to this GitHub repo https://github.com/vinhnx/Clendar.

**Comment by prabal4546** [comment]
Hi, I have opened PR #233 for this issue, can you please check if it's alright?

**Comment by vinhnx** [comment]
hi @prabal4546, I have one small remark on https://github.com/vinhnx/Clendar/pull/233/files/38d6585491be2ff285fab994955e2e1a2d2fee8e#diff-daa6f9e816904f37714eef04c2217dfa6f51d1b5d4c4aec242fa453c562afb2e, please help take a look.

Thank you so much!

**Comment by vinhnx** [comment]
hi @prabal4546, I have submitted a release with this change. Thank you again!
