### ISSUE TITLE
App version 3.6.0 crash on iOS 15.6.1

### ISSUE THREAD

**Issue by chriscapisce** [vinhnx/Clendar#244]
App version 3.6.0 crashes on iOS 15.6.1. The app shortly shows white screen after opening and than closes/ crashes.. version 3.5.0 was fine. I just bought Clendar+.

**Comment by chriscapisce** [comment]
Switched from iPhone 6s to an SE 2022. Still same issue....

**Comment by ParoTheParrot** [comment]
Same höre, iPad Pro11 :-(

**Comment by vinhnx** [comment]
Hi all. Sorry for the inconvenience. I didn't get the email notification. 

I will look into the issue and provide a fix build soon. Thank you!

**Comment by vinhnx** [comment]
Hi everyone. I have identified the issue and am about to submit the fix soon to the App Store. 

The problem was missing symbol caused by an modifier when run on iOS 15. 

Thank you for reporting the issue!

**Comment by vinhnx** [comment]
Hi everyone, The new update v3.6.1 is now live 

📲 https://apps.apple.com/app/clendar-minimal-calendar/id1548102041

**Comment by chriscapisce** [comment]
That solved the problem for me, thanks.
