### ISSUE TITLE
app store privacy policy link error

### ISSUE THREAD

**Issue by postprivee** [vinhnx/Clendar#257]
ios app store [privacy policy](https://www.clendar.info/privacy.html) gives not found error

**Comment by vinhnx** [comment]
Hi @postprivee thank you for reporting this. I will update the lading page

Sorry for the late reply I missed your notication.

**Comment by vinhnx** [comment]
The landing page has change to https://vinhnx.github.io/clendar-site/privacy.html

Since I have no longer use the clendar.info domain

Thank you!
