### ISSUE TITLE
Command PhaseScriptExecution failed with a nonzero exit code Error

### ISSUE THREAD

**Issue by susumu-nakoshi** [vinhnx/Clendar#263]
<img width="265" alt="Screenshot 2023-10-09 at 22 31 46" src="https://github.com/vinhnx/Clendar/assets/138769908/7eeaed7a-92d1-4b66-9e66-49cbc76753a9">

<Environment>
  Mac M2 Max
  Xcode 15.0
  macOS 14.1 Beta

**Comment by vinhnx** [comment]
Hi @susumu-nakoshi , sorry I missed the notification 

would you please give more detail, by clicking on the Xcode error log and paste it here. So I could take a look

Meanwhile you can try downloading the latest Xcode 15 to try it.
Let me know if you still having error, thank you!
