### ISSUE TITLE
add Italian localization

### ISSUE THREAD

**Issue by vinhnx** [vinhnx/Clendar#264]

**Comment by Levyathanus** [comment]
Hi, 
do you need help translating for in-app localization or for this project documentation?
I'm not a Swift programmer but if you need help for the localization of terms/sentences I would be glad to contribute.

**Comment by vinhnx** [comment]
> Hi, 
> 
> do you need help translating for in-app localization or for this project documentation?
> 
> I'm not a Swift programmer but if you need help for the localization of terms/sentences I would be glad to contribute.

Hi @Levyathanus Thank you for your kind suggestion! Sure that would be wonderful if you can help translating into Italian. 

You can reference the base English translation here 

https://github.com/Clendar/Resources/Localization/en.lproj/Localizable.strings

Thank you so much! Let me know if you have any trouble.

**Comment by Levyathanus** [comment]
Hi @vinhnx, thank you for your response and references.
I've opened a PR for this. If you need further support please consider assigning this issue to me!

Thank you, have a nice day!

**Comment by vinhnx** [comment]
> Hi @vinhnx, thank you for your response and references.
> 
> I've opened a PR for this. If you need further support please consider assigning this issue to me!
> 
> 
> 
> Thank you, have a nice day!

Hi @Levyathanus thank you so very much! This means a lot to me. 

Have a good day and happy weekend!

**Comment by vinhnx** [comment]
done #265 

Huge thank to @Levyathanus ! 💯
